- uobtheatre/bookings/serializers.py
- uobtheatre/bookings/test/test_serializers.py
- uobtheatre/productions/test/test_views.py
- uobtheatre/productions/views.py
- Added performance discount view
> Added tests for performance_discount_view

- Makefile
> Updated Makefile with user for migrations

- uobtheatre/bookings/models.py
- uobtheatre/productions/models.py
- uobtheatre/productions/schema.py
- uobtheatre/schema.py
- uobtheatre/societies/schema.py
- uobtheatre/societies/test/test_schema.py
- uobtheatre/venues/models.py
- uobtheatre/venues/test/test_schema.py
- Added societies to graphql schema
- Updated venues schema tests
> Added societies to schema

- Makefile
- schema.graphql
Added graphene schema and export
> Added schema export

- uobtheatre/productions/schema.py
- uobtheatre/productions/test/test_schema.py
Added venue to performance schema
> Added venue to performance schema

- uobtheatre/productions/schema.py
- uobtheatre/productions/test/test_schema.py
```
{
performance(id: "UGVyZm9ybWFuY2VOb2RlOjE=") {
id
}
}
```
> Added performance by id

- .pre-commit-config.yaml
- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_schema.py
- uobtheatre/payments/schema.py
- uobtheatre/payments/test/test_schema.py
- uobtheatre/productions/schema.py
- uobtheatre/productions/test/test_schema.py
- uobtheatre/utils/enums.py
- uobtheatre/utils/filters.py
- uobtheatre/utils/schema.py
Return enums as objects, with value and description
> Enum fields

- .github/workflows/generate-schema.yml
- schema.graphql
> Generate schema on pr

- .devcontainer/devcontainer.json
- .pylintrc
- compose/local/django/Dockerfile
- compose/production/django/Dockerfile
- local.yml
- schema.graphql
- uobtheatre/bookings/test/test_mutations.py
- uobtheatre/productions/models.py
- uobtheatre/productions/schema.py
- uobtheatre/productions/test/test_models.py
- uobtheatre/productions/test/test_schema.py
TODO:
- Refactor the tickets queries to be better & lazy
> feat: Tickets Breakdown

- requirements/base.txt
- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_schema.py
- uobtheatre/productions/models.py
- uobtheatre/schema.py
Searches through bookings using: user first name, user last name, user email and boooking reference.
> Added bookings search

- uobtheatre/productions/admin.py
Can set object-level permissions for productions in Django admin pannel
> Added guardian production admin

- Makefile
- config/settings/common.py
- config/settings/local.py
- config/settings/production.py
- requirements/base.txt
- requirements/production.txt
- schema.graphql
- uobtheatre/users/admin.py
- uobtheatre/users/templates/emails/activation_email.html
- uobtheatre/users/test/test_schema.py
- Send emails with SES
- Email verification is required to login
- Added user status model to admin so user can be verified in admin panel
- Added example register email
> Email setup

- config/settings/common.py
`email_verify` -> `email-verify`
> Update email verify path

- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_schema.py
Added order by performance start time.
@atoff :)
> add order by performance start

- uobtheatre/bookings/admin.py
- uobtheatre/bookings/models.py
- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_models.py
- uobtheatre/bookings/test/test_schema.py
- uobtheatre/productions/models.py
- uobtheatre/productions/test/test_models.py
> adding cached properties

- local.yml
- schema.graphql
- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_mutations.py
- uobtheatre/payments/payment_methods.py
- uobtheatre/utils/exceptions.py
- uobtheatre/utils/test/test_exceptions.py
> feat: Admin Discount on mutations

- .devcontainer/devcontainer.json
- schema.graphql
- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_mutations.py
- uobtheatre/productions/models.py
- uobtheatre/productions/schema.py
- uobtheatre/productions/test/factories.py
- uobtheatre/productions/test/test_models.py
- uobtheatre/productions/test/test_schema.py
- uobtheatre/utils/test/test_schema.py
> Fix: Prevent bookings in past

- conftest.py
- schema.graphql
- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/test_mutations.py
- uobtheatre/payments/payment_methods.py
- uobtheatre/payments/test/factories.py
- uobtheatre/utils/exceptions.py
- uobtheatre/utils/test/test_exceptions.py
- Make square error messages from the API more informative
- Shift responsibility for supplying the idempotency key to frontend
> fix: Square fixes

- uobtheatre/bookings/schema.py
- uobtheatre/bookings/test/factories.py
- uobtheatre/bookings/test/test_mutations.py
Allows for free bookings (by not creating a payment/parsing the payment provider)
Also enforces the need for a booking to have at least one ticket to be paid for
Closes #190
> feat: Free bookings and other stuff

- schema.graphql
- uobtheatre/productions/models.py
- uobtheatre/productions/schema.py
- uobtheatre/productions/test/test_schema.py
- uobtheatre/utils/schema.py
- uobtheatre/utils/test/test_schema.py
> feat: Production admin filtering

- requirements/local.txt
- uobtheatre/payments/models.py
- uobtheatre/payments/payment_methods.py
- uobtheatre/payments/test/factories.py
- uobtheatre/payments/test/test_models.py
- uobtheatre/payments/test/test_payment_methods.py
- uobtheatre/reports/reports.py
- uobtheatre/reports/test/test_reports.py
On report generation fetch any missing provider fees
> Fetch empty processing fees on report generation

- uobtheatre/payments/admin.py
- Fix sync payment admin function
- Add payment filters
> Fixed payment sync payment action

- requirements/base.txt
Reverts BristolSTA/uobtheatre-api#349
> Revert "Bump django-tiptap from 0.0.10 to 0.0.12"

- requirements/base.txt
Reverts BristolSTA/uobtheatre-api#389
> Revert "Bump django-tiptap from 0.0.10 to 0.0.18"

- schema.graphql
- uobtheatre/images/abilities.py
- uobtheatre/images/test/test_abilities.py
- uobtheatre/societies/schema.py
* allow people with add production ability to upload image
* Add user has permissiosn filter to society
* add test
* Updated schema
* fix test
* fix test
Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
> Release image upload permissions fix

- uobtheatre/bookings/mutations.py
- uobtheatre/bookings/test/test_mutations.py
- uobtheatre/productions/abilities.py
- uobtheatre/productions/test/test_abilities.py
> fix: Booking creation policy

- requirements/base.txt
- requirements/local.txt
Reverts BristolSTA/uobtheatre-api#428
> Revert "Fix/missing deps for queue refunds celery"

- uobtheatre/productions/mutations.py
- uobtheatre/productions/test/test_mutations.py
> fix: Only check society permission if changed

- .github/workflows/python-checks.yml
- uobtheatre/productions/models.py
- uobtheatre/productions/test/test_models.py
> feat: Consider discounts in min ticket price

- uobtheatre/productions/models.py
- uobtheatre/productions/test/test_models.py
> booked_users queryset filter to PAID bookings

- uobtheatre/payments/models.py
- uobtheatre/productions/models.py
- uobtheatre/users/abilities.py
- uobtheatre/users/models.py
- uobtheatre/users/test/test_models.py
- uobtheatre/utils/exceptions.py
- uobtheatre/utils/schema.py
- uobtheatre/utils/test/test_exceptions.py
yeah alex thaught me things permission got fixed
> fixing giving permissions permissions

- .github/dependabot.yml
Update dependabot open PR limit from 5 to 20.
> Update Dependabot limit

- requirements/local.txt
- schema.graphql
- uobtheatre/productions/forms.py
- uobtheatre/societies/migrations/0007_society_su_status.py
- uobtheatre/societies/schema.py
A couple of quick fixes that I failed to properly catch in previous features. Whoop!
> fix: Expose su_status on SocietyNode and production_alert in ProductionForm

- schema.graphql
- uobtheatre/bookings/models.py
- uobtheatre/bookings/schema.py
Acompanies [Web PR 688](https://github.com/BristolSTA/uobtheatre-web/pull/688)
> feat: API work to expose miscCosts for frontend query
